spring.application.name=sistema-almacen
# Configuraci\u00f3n del servidor de la aplicaci\u00f3n
server.port=8080

# Conexi\u00f3n a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/almacen_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Croker765
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuraci\u00f3n de JPA / Hibernate
# "none" le dice a Spring que no modifique la BD, ya que la creamos con tu script SQL.
spring.jpa.hibernate.ddl-auto=none

# Muestra en la consola de NetBeans las consultas SQL que ejecuta Spring Boot (\u00fatil para aprender y depurar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true